### ISSUE TITLE
Newer Kotlin versions create querybeans only on the first build

### ISSUE THREAD

**Issue by tobias-** [ebean-orm-tools/ebean-gradle-plugin#14]
Steps to reproduce:

Check out
https://github.com/ebean-orm-examples/example-gradle-kotlin

Change from `1.1.2-2` to either of `1.1.51`, `1.2.0` or `1.2.10`. As a note, 1.1.2-2 works every time in this project.

By changing the version of kotlin used, the build will work exactly once, but after a `gradlew clean`, it will not work until either `example-gradle-kotlin/.gradle` folder is removed or certain classpath changes (most reliably by changing kotlin version).

First time `gradlew clean build` is run, it works. second time (and all after it) it fails. I've tried using gradle 4.4.1 and 3.0, but it doesn't seem to matter.

This may be a bug in Kotlin kapt3, but I can't find any references to such a bug.

**Comment by rbygrave** [comment]
I don't believe this is reproducable any more?
