### ISSUE TITLE
the ebean enhancer isn't silent

### ISSUE THREAD

**Issue by egandro** [ebean-orm-tools/ebean-gradle-plugin#20]
The ebean gradle plugin isn't "silent" when gradle is started with "-q".

$ gradle -q clean build

We get lot's of messages like this:

ebean-enhance> cls: com/foo/bar/entity/Query  msg: enhanced
enhancement prior to running tests

Nothing wrong here - but we use -q to have the continious integration build verbose level stripped down just to errors and warnings.

Please patch :)

**Comment by rbygrave** [comment]
Please submit a patch :)

**Comment by egandro** [comment]
gradle -q ... >/dev/null

**Comment by egandro** [comment]
I just found it out :)

You guys are using "logger.info"

According to this: https://docs.gradle.org/current/userguide/custom_plugins.html
it's

logger.quiet "Writing message 'Hi from Gradle' to file"

Can you change this?

**Comment by rbygrave** [comment]
Ok, should be sorted in 11.13.1
