### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property name has not been initialized

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm-tools/ebean-gradle-plugin#5]
Gradle suite > Gradle test > org.example.domain.CustomerTest.save FAILED
    kotlin.UninitializedPropertyAccessException: lateinit property name has not been initialized
        at org.example.domain.query.QCustomer.getName(QCustomer.kt:27)
        at org.example.domain.CustomerTest.save(CustomerTest.kt:20)

**Comment by rbygrave** [comment]
So this is when we use Kotlin query beans with this gradle plugin.

The underlying issue here is with the query bean enhancement and dealing with kotlin query beans (using kotlin lateinit properties).  There is a fix to the ebean-agent to fix this issue ... and using the updated agent will fix this plugin.

**Comment by igorcavalcante** [comment]
Hello, i have this problem, how can i use the updated agent?. Thank you

**Comment by rbygrave** [comment]
@igorcavalcante ... just use an updated version of the plugin - e.g. 10.2.3

Note that questions are better directed to the forum - https://groups.google.com/forum/#!forum/ebean ... more people watching that etc.

**Comment by cheese-stands-alone** [comment]
I am still having this issue with version 10.2.3. I created a sample project to recreate the issue.
[https://github.com/rwhite226/ebean-test](url)
