### ISSUE TITLE
plugin searchs for validation-api-sources.jar when it actually has a different filename

### ISSUE THREAD

**Issue by ghost** [ebean-orm-tools/ebean-gradle-plugin#8]
I added this plugin to build.gradle and set it up almost like the readme but it fails with this message :  

> > :processResources
> perform enhancement for task: processResources
> :processResources FAILED
> :autoLintGradle
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':processResources'.
> > Could not resolve all files for configuration ':compileClasspath'.
>    > Could not find validation-api-sources.jar (javax.validation:validation-api:1.1.0.Final).
>      Searched in the following locations:
>          file:/home/abd/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final-sources.jar
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I don't know exactly what's the problem because `validation-api` sources jar exists in maven Central repo, probably the plugin is searching for a wrong filename or I'm missing something.   

How to resolve this problem ?

**Comment by rbygrave** [comment]
I'll close this issue ... please ask questions on the forum - https://groups.google.com/forum/#!forum/ebean

Thanks.
