### ISSUE TITLE
Publish to Gradle Plug-in Portal (rename to io.ebean as a consequence)

### ISSUE THREAD

**Issue by aadrian** [ebean-orm-tools/ebean-gradle-plugin#9]
Please add the plug-in to the Gradle Plug-in portal.

It doesn't seems to be there :( :
https://plugins.gradle.org/search?term=ebean

Thank you.

**Comment by rbygrave** [comment]
Right, in doing so note that we need to rename the plugin from `ebean` to `io.ebean`.
